"""集中导入所有模型，便于 Alembic 与 create_all 发现表结构。"""

from app.models.base import (
    AIInteractionTypeEnum,
    AIStatusEnum,
    EquipmentStatusEnum,
    FaultReportStatusEnum,
    KnowledgeCategoryEnum,
    MaintenanceLogTypeEnum,
    PriorityEnum,
    RiskLevelEnum,
    RoleEnum,
    UrgencyEnum,
    WorkOrderStatusEnum,
    WorkOrderTypeEnum,
)
from app.models.equipment import Equipment, EquipmentType, FaultCode, SparePart
from app.models.fault import FaultReport
from app.models.intelligence import (
    AgentRun,
    AnomalyEvent,
    EquipmentSensor,
    FaultDiagnosis,
    MaintenanceRecommendation,
    MaintenanceVerification,
    OperationApproval,
    RiskPrediction,
    SparePartReservation,
    TelemetryRecord,
    ToolInvocation,
)
from app.models.knowledge import (
    AcceptanceRecord,
    AIInteraction,
    KnowledgeArticle,
    KnowledgeChunk,
    Notification,
)
from app.models.maintenance import (
    Attachment,
    LaborEntry,
    MaintenanceLog,
    WorkOrderReport,
    WorkOrderSparePart,
)
from app.models.user import Skill, TechnicianProfile, User
from app.models.workorder import (
    WorkOrder,
    WorkOrderAssignment,
    WorkOrderChecklistItem,
    WorkOrderStatusHistory,
)

__all__ = [
    "AIInteraction",
    "AIInteractionTypeEnum",
    "AIStatusEnum",
    "AcceptanceRecord",
    "AgentRun",
    "AnomalyEvent",
    "Attachment",
    "Equipment",
    "EquipmentSensor",
    "EquipmentStatusEnum",
    "EquipmentType",
    "FaultCode",
    "FaultDiagnosis",
    "FaultReport",
    "FaultReportStatusEnum",
    "KnowledgeArticle",
    "KnowledgeCategoryEnum",
    "KnowledgeChunk",
    "LaborEntry",
    "MaintenanceLog",
    "MaintenanceLogTypeEnum",
    "MaintenanceRecommendation",
    "MaintenanceVerification",
    "Notification",
    "OperationApproval",
    "PriorityEnum",
    "RiskLevelEnum",
    "RiskPrediction",
    "RoleEnum",
    "Skill",
    "SparePart",
    "SparePartReservation",
    "TechnicianProfile",
    "TelemetryRecord",
    "ToolInvocation",
    "UrgencyEnum",
    "User",
    "WorkOrder",
    "WorkOrderAssignment",
    "WorkOrderChecklistItem",
    "WorkOrderReport",
    "WorkOrderSparePart",
    "WorkOrderStatusEnum",
    "WorkOrderStatusHistory",
    "WorkOrderTypeEnum",
]
